/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DayComponentsMapperId model module.
 * @module api-course-service/models/DayComponentsMapperId
 * @version 1.0.0
 */
class DayComponentsMapperId {
    /**
     * Constructs a new <code>DayComponentsMapperId</code>.
     * Composite ID for DayComponentsMapper
     * @alias module:api-course-service/models/DayComponentsMapperId
     * @param dayBlueprintUuid {String} UUID for a Day Blueprint
     * @param componentUuid {String} UUID for a Day Component
     */
    constructor(dayBlueprintUuid, componentUuid) { 
        
        DayComponentsMapperId.initialize(this, dayBlueprintUuid, componentUuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, dayBlueprintUuid, componentUuid) { 
        obj['day_blueprint_uuid'] = dayBlueprintUuid;
        obj['component_uuid'] = componentUuid;
    }

    /**
     * Constructs a <code>DayComponentsMapperId</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:api-course-service/models/DayComponentsMapperId} obj Optional instance to populate.
     * @return {module:api-course-service/models/DayComponentsMapperId} The populated <code>DayComponentsMapperId</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DayComponentsMapperId();

            if (data.hasOwnProperty('day_blueprint_uuid')) {
                obj['day_blueprint_uuid'] = ApiClient.convertToType(data['day_blueprint_uuid'], 'String');
            }
            if (data.hasOwnProperty('component_uuid')) {
                obj['component_uuid'] = ApiClient.convertToType(data['component_uuid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DayComponentsMapperId</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DayComponentsMapperId</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DayComponentsMapperId.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['day_blueprint_uuid'] && !(typeof data['day_blueprint_uuid'] === 'string' || data['day_blueprint_uuid'] instanceof String)) {
            throw new Error("Expected the field `day_blueprint_uuid` to be a primitive type in the JSON string but got " + data['day_blueprint_uuid']);
        }
        // ensure the json data is a string
        if (data['component_uuid'] && !(typeof data['component_uuid'] === 'string' || data['component_uuid'] instanceof String)) {
            throw new Error("Expected the field `component_uuid` to be a primitive type in the JSON string but got " + data['component_uuid']);
        }

        return true;
    }


}

DayComponentsMapperId.RequiredProperties = ["day_blueprint_uuid", "component_uuid"];

/**
 * UUID for a Day Blueprint
 * @member {String} day_blueprint_uuid
 */
DayComponentsMapperId.prototype['day_blueprint_uuid'] = undefined;

/**
 * UUID for a Day Component
 * @member {String} component_uuid
 */
DayComponentsMapperId.prototype['component_uuid'] = undefined;






export default DayComponentsMapperId;

