/* tslint:disable */
/* eslint-disable */
/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FormInstanceId } from './FormInstanceId';
import {
    FormInstanceIdFromJSON,
    FormInstanceIdFromJSONTyped,
    FormInstanceIdToJSON,
    FormInstanceIdToJSONTyped,
} from './FormInstanceId';

/**
 * Specific instance of a form for a user
 * @export
 * @interface FormInstance
 */
export interface FormInstance {
    /**
     * 
     * @type {FormInstanceId}
     * @memberof FormInstance
     */
    id: FormInstanceId;
    /**
     * True if form is completed, false otherwise
     * @type {boolean}
     * @memberof FormInstance
     */
    status: boolean;
}

/**
 * Check if a given object implements the FormInstance interface.
 */
export function instanceOfFormInstance(value: object): value is FormInstance {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function FormInstanceFromJSON(json: any): FormInstance {
    return FormInstanceFromJSONTyped(json, false);
}

export function FormInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'id': FormInstanceIdFromJSON(json['id']),
        'status': json['status'],
    };
}

export function FormInstanceToJSON(json: any): FormInstance {
    return FormInstanceToJSONTyped(json, false);
}

export function FormInstanceToJSONTyped(value?: FormInstance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': FormInstanceIdToJSON(value['id']),
        'status': value['status'],
    };
}

