/* tslint:disable */
/* eslint-disable */
/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Composite ID for FormFieldMapper
 * @export
 * @interface FormFieldMapperId
 */
export interface FormFieldMapperId {
    /**
     * UUID for a Form Blueprint
     * @type {string}
     * @memberof FormFieldMapperId
     */
    formBlueprintUuid: string;
    /**
     * UUID for a Form Field
     * @type {string}
     * @memberof FormFieldMapperId
     */
    fieldUuid: string;
}

/**
 * Check if a given object implements the FormFieldMapperId interface.
 */
export function instanceOfFormFieldMapperId(value: object): value is FormFieldMapperId {
    if (!('formBlueprintUuid' in value) || value['formBlueprintUuid'] === undefined) return false;
    if (!('fieldUuid' in value) || value['fieldUuid'] === undefined) return false;
    return true;
}

export function FormFieldMapperIdFromJSON(json: any): FormFieldMapperId {
    return FormFieldMapperIdFromJSONTyped(json, false);
}

export function FormFieldMapperIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormFieldMapperId {
    if (json == null) {
        return json;
    }
    return {
        
        'formBlueprintUuid': json['form_blueprint_uuid'],
        'fieldUuid': json['field_uuid'],
    };
}

export function FormFieldMapperIdToJSON(json: any): FormFieldMapperId {
    return FormFieldMapperIdToJSONTyped(json, false);
}

export function FormFieldMapperIdToJSONTyped(value?: FormFieldMapperId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'form_blueprint_uuid': value['formBlueprintUuid'],
        'field_uuid': value['fieldUuid'],
    };
}

