/* tslint:disable */
/* eslint-disable */
/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Composite ID for TaskInstance
 * @export
 * @interface TaskInstanceId
 */
export interface TaskInstanceId {
    /**
     * UUID for a Task Blueprint
     * @type {string}
     * @memberof TaskInstanceId
     */
    taskBlueprintUuid: string;
    /**
     * UUID for a User
     * @type {string}
     * @memberof TaskInstanceId
     */
    userUuid: string;
}

/**
 * Check if a given object implements the TaskInstanceId interface.
 */
export function instanceOfTaskInstanceId(value: object): value is TaskInstanceId {
    if (!('taskBlueprintUuid' in value) || value['taskBlueprintUuid'] === undefined) return false;
    if (!('userUuid' in value) || value['userUuid'] === undefined) return false;
    return true;
}

export function TaskInstanceIdFromJSON(json: any): TaskInstanceId {
    return TaskInstanceIdFromJSONTyped(json, false);
}

export function TaskInstanceIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskInstanceId {
    if (json == null) {
        return json;
    }
    return {
        
        'taskBlueprintUuid': json['task_blueprint_uuid'],
        'userUuid': json['user_uuid'],
    };
}

export function TaskInstanceIdToJSON(json: any): TaskInstanceId {
    return TaskInstanceIdToJSONTyped(json, false);
}

export function TaskInstanceIdToJSONTyped(value?: TaskInstanceId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task_blueprint_uuid': value['taskBlueprintUuid'],
        'user_uuid': value['userUuid'],
    };
}

