/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FormBlueprint from './FormBlueprint';
import FormInstance from './FormInstance';

/**
 * The FormDTO model module.
 * @module api-content-service/models/FormDTO
 * @version 1.0.0
 */
class FormDTO {
    /**
     * Constructs a new <code>FormDTO</code>.
     * @alias module:api-content-service/models/FormDTO
     * @param blueprint {module:api-content-service/models/FormBlueprint} 
     * @param instance {module:api-content-service/models/FormInstance} 
     */
    constructor(blueprint, instance) { 
        
        FormDTO.initialize(this, blueprint, instance);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, blueprint, instance) { 
        obj['blueprint'] = blueprint;
        obj['instance'] = instance;
    }

    /**
     * Constructs a <code>FormDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:api-content-service/models/FormDTO} obj Optional instance to populate.
     * @return {module:api-content-service/models/FormDTO} The populated <code>FormDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FormDTO();

            if (data.hasOwnProperty('blueprint')) {
                obj['blueprint'] = FormBlueprint.constructFromObject(data['blueprint']);
            }
            if (data.hasOwnProperty('instance')) {
                obj['instance'] = FormInstance.constructFromObject(data['instance']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FormDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FormDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FormDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `blueprint`
        if (data['blueprint']) { // data not null
          FormBlueprint.validateJSON(data['blueprint']);
        }
        // validate the optional field `instance`
        if (data['instance']) { // data not null
          FormInstance.validateJSON(data['instance']);
        }

        return true;
    }


}

FormDTO.RequiredProperties = ["blueprint", "instance"];

/**
 * @member {module:api-content-service/models/FormBlueprint} blueprint
 */
FormDTO.prototype['blueprint'] = undefined;

/**
 * @member {module:api-content-service/models/FormInstance} instance
 */
FormDTO.prototype['instance'] = undefined;






export default FormDTO;

