/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FormFieldMapperId from './FormFieldMapperId';

/**
 * The FormFieldMapper model module.
 * @module api-content-service/models/FormFieldMapper
 * @version 1.0.0
 */
class FormFieldMapper {
    /**
     * Constructs a new <code>FormFieldMapper</code>.
     * Mapping a field within a form
     * @alias module:api-content-service/models/FormFieldMapper
     * @param id {module:api-content-service/models/FormFieldMapperId} 
     * @param sortOrder {Number} Order or position within a list
     */
    constructor(id, sortOrder) { 
        
        FormFieldMapper.initialize(this, id, sortOrder);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, sortOrder) { 
        obj['id'] = id;
        obj['sortOrder'] = sortOrder;
    }

    /**
     * Constructs a <code>FormFieldMapper</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:api-content-service/models/FormFieldMapper} obj Optional instance to populate.
     * @return {module:api-content-service/models/FormFieldMapper} The populated <code>FormFieldMapper</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FormFieldMapper();

            if (data.hasOwnProperty('id')) {
                obj['id'] = FormFieldMapperId.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('sortOrder')) {
                obj['sortOrder'] = ApiClient.convertToType(data['sortOrder'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FormFieldMapper</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FormFieldMapper</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FormFieldMapper.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `id`
        if (data['id']) { // data not null
          FormFieldMapperId.validateJSON(data['id']);
        }

        return true;
    }


}

FormFieldMapper.RequiredProperties = ["id", "sortOrder"];

/**
 * @member {module:api-content-service/models/FormFieldMapperId} id
 */
FormFieldMapper.prototype['id'] = undefined;

/**
 * Order or position within a list
 * @member {Number} sortOrder
 */
FormFieldMapper.prototype['sortOrder'] = undefined;






export default FormFieldMapper;

