/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FormFieldMapperId model module.
 * @module api-content-service/models/FormFieldMapperId
 * @version 1.0.0
 */
class FormFieldMapperId {
    /**
     * Constructs a new <code>FormFieldMapperId</code>.
     * Composite ID for FormFieldMapper
     * @alias module:api-content-service/models/FormFieldMapperId
     * @param formBlueprintUuid {String} UUID for a Form Blueprint
     * @param fieldUuid {String} UUID for a Form Field
     */
    constructor(formBlueprintUuid, fieldUuid) { 
        
        FormFieldMapperId.initialize(this, formBlueprintUuid, fieldUuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, formBlueprintUuid, fieldUuid) { 
        obj['form_blueprint_uuid'] = formBlueprintUuid;
        obj['field_uuid'] = fieldUuid;
    }

    /**
     * Constructs a <code>FormFieldMapperId</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:api-content-service/models/FormFieldMapperId} obj Optional instance to populate.
     * @return {module:api-content-service/models/FormFieldMapperId} The populated <code>FormFieldMapperId</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FormFieldMapperId();

            if (data.hasOwnProperty('form_blueprint_uuid')) {
                obj['form_blueprint_uuid'] = ApiClient.convertToType(data['form_blueprint_uuid'], 'String');
            }
            if (data.hasOwnProperty('field_uuid')) {
                obj['field_uuid'] = ApiClient.convertToType(data['field_uuid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FormFieldMapperId</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FormFieldMapperId</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FormFieldMapperId.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['form_blueprint_uuid'] && !(typeof data['form_blueprint_uuid'] === 'string' || data['form_blueprint_uuid'] instanceof String)) {
            throw new Error("Expected the field `form_blueprint_uuid` to be a primitive type in the JSON string but got " + data['form_blueprint_uuid']);
        }
        // ensure the json data is a string
        if (data['field_uuid'] && !(typeof data['field_uuid'] === 'string' || data['field_uuid'] instanceof String)) {
            throw new Error("Expected the field `field_uuid` to be a primitive type in the JSON string but got " + data['field_uuid']);
        }

        return true;
    }


}

FormFieldMapperId.RequiredProperties = ["form_blueprint_uuid", "field_uuid"];

/**
 * UUID for a Form Blueprint
 * @member {String} form_blueprint_uuid
 */
FormFieldMapperId.prototype['form_blueprint_uuid'] = undefined;

/**
 * UUID for a Form Field
 * @member {String} field_uuid
 */
FormFieldMapperId.prototype['field_uuid'] = undefined;






export default FormFieldMapperId;

