/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TaskInstanceId model module.
 * @module api-content-service/models/TaskInstanceId
 * @version 1.0.0
 */
class TaskInstanceId {
    /**
     * Constructs a new <code>TaskInstanceId</code>.
     * Composite ID for TaskInstance
     * @alias module:api-content-service/models/TaskInstanceId
     * @param taskBlueprintUuid {String} UUID for a Task Blueprint
     * @param userUuid {String} UUID for a User
     */
    constructor(taskBlueprintUuid, userUuid) { 
        
        TaskInstanceId.initialize(this, taskBlueprintUuid, userUuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, taskBlueprintUuid, userUuid) { 
        obj['task_blueprint_uuid'] = taskBlueprintUuid;
        obj['user_uuid'] = userUuid;
    }

    /**
     * Constructs a <code>TaskInstanceId</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:api-content-service/models/TaskInstanceId} obj Optional instance to populate.
     * @return {module:api-content-service/models/TaskInstanceId} The populated <code>TaskInstanceId</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaskInstanceId();

            if (data.hasOwnProperty('task_blueprint_uuid')) {
                obj['task_blueprint_uuid'] = ApiClient.convertToType(data['task_blueprint_uuid'], 'String');
            }
            if (data.hasOwnProperty('user_uuid')) {
                obj['user_uuid'] = ApiClient.convertToType(data['user_uuid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TaskInstanceId</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TaskInstanceId</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TaskInstanceId.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['task_blueprint_uuid'] && !(typeof data['task_blueprint_uuid'] === 'string' || data['task_blueprint_uuid'] instanceof String)) {
            throw new Error("Expected the field `task_blueprint_uuid` to be a primitive type in the JSON string but got " + data['task_blueprint_uuid']);
        }
        // ensure the json data is a string
        if (data['user_uuid'] && !(typeof data['user_uuid'] === 'string' || data['user_uuid'] instanceof String)) {
            throw new Error("Expected the field `user_uuid` to be a primitive type in the JSON string but got " + data['user_uuid']);
        }

        return true;
    }


}

TaskInstanceId.RequiredProperties = ["task_blueprint_uuid", "user_uuid"];

/**
 * UUID for a Task Blueprint
 * @member {String} task_blueprint_uuid
 */
TaskInstanceId.prototype['task_blueprint_uuid'] = undefined;

/**
 * UUID for a User
 * @member {String} user_uuid
 */
TaskInstanceId.prototype['user_uuid'] = undefined;






export default TaskInstanceId;

