/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import FormBlueprint from '../models/FormBlueprint';
import FormDTO from '../models/FormDTO';
import FormFieldMapper from '../models/FormFieldMapper';
import FormInstance from '../models/FormInstance';
import Media from '../models/Media';
import TaskBlueprint from '../models/TaskBlueprint';
import TaskDTO from '../models/TaskDTO';
import TaskInstance from '../models/TaskInstance';

/**
* Default service.
* @module api-content-service/controllers/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api-content-service/controllers/DefaultApi
    * @class
    * @param {module:api-content-service/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:api-content-service/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the formFieldMapperFormBlueprintUuidFieldUuidDelete operation.
     * @callback module:api-content-service/controllers/DefaultApi~formFieldMapperFormBlueprintUuidFieldUuidDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a form-field mapping (admin only)
     * @param {String} formBlueprintUuid The UUID of the form blueprint
     * @param {String} fieldUuid The UUID of the form field
     * @param {module:api-content-service/controllers/DefaultApi~formFieldMapperFormBlueprintUuidFieldUuidDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    formFieldMapperFormBlueprintUuidFieldUuidDelete(formBlueprintUuid, fieldUuid, callback) {
      let postBody = null;
      // verify the required parameter 'formBlueprintUuid' is set
      if (formBlueprintUuid === undefined || formBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'formBlueprintUuid' when calling formFieldMapperFormBlueprintUuidFieldUuidDelete");
      }
      // verify the required parameter 'fieldUuid' is set
      if (fieldUuid === undefined || fieldUuid === null) {
        throw new Error("Missing the required parameter 'fieldUuid' when calling formFieldMapperFormBlueprintUuidFieldUuidDelete");
      }

      let pathParams = {
        'form_blueprint_uuid': formBlueprintUuid,
        'field_uuid': fieldUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['admin_jwt'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/form-field-mapper/{form_blueprint_uuid}/{field_uuid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formFieldMapperFormBlueprintUuidFieldUuidGet operation.
     * @callback module:api-content-service/controllers/DefaultApi~formFieldMapperFormBlueprintUuidFieldUuidGetCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/FormFieldMapper} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a specific form-field mapping
     * @param {String} formBlueprintUuid The UUID of the form blueprint
     * @param {String} fieldUuid The UUID of the form field
     * @param {module:api-content-service/controllers/DefaultApi~formFieldMapperFormBlueprintUuidFieldUuidGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/FormFieldMapper}
     */
    formFieldMapperFormBlueprintUuidFieldUuidGet(formBlueprintUuid, fieldUuid, callback) {
      let postBody = null;
      // verify the required parameter 'formBlueprintUuid' is set
      if (formBlueprintUuid === undefined || formBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'formBlueprintUuid' when calling formFieldMapperFormBlueprintUuidFieldUuidGet");
      }
      // verify the required parameter 'fieldUuid' is set
      if (fieldUuid === undefined || fieldUuid === null) {
        throw new Error("Missing the required parameter 'fieldUuid' when calling formFieldMapperFormBlueprintUuidFieldUuidGet");
      }

      let pathParams = {
        'form_blueprint_uuid': formBlueprintUuid,
        'field_uuid': fieldUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['admin_jwt'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = FormFieldMapper;
      return this.apiClient.callApi(
        '/form-field-mapper/{form_blueprint_uuid}/{field_uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formFieldMapperFormBlueprintUuidFieldUuidPut operation.
     * @callback module:api-content-service/controllers/DefaultApi~formFieldMapperFormBlueprintUuidFieldUuidPutCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/FormFieldMapper} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a form-field mapping (admin only)
     * @param {String} formBlueprintUuid The UUID of the form blueprint
     * @param {String} fieldUuid The UUID of the form field
     * @param {module:api-content-service/models/FormFieldMapper} formFieldMapper 
     * @param {module:api-content-service/controllers/DefaultApi~formFieldMapperFormBlueprintUuidFieldUuidPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/FormFieldMapper}
     */
    formFieldMapperFormBlueprintUuidFieldUuidPut(formBlueprintUuid, fieldUuid, formFieldMapper, callback) {
      let postBody = formFieldMapper;
      // verify the required parameter 'formBlueprintUuid' is set
      if (formBlueprintUuid === undefined || formBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'formBlueprintUuid' when calling formFieldMapperFormBlueprintUuidFieldUuidPut");
      }
      // verify the required parameter 'fieldUuid' is set
      if (fieldUuid === undefined || fieldUuid === null) {
        throw new Error("Missing the required parameter 'fieldUuid' when calling formFieldMapperFormBlueprintUuidFieldUuidPut");
      }
      // verify the required parameter 'formFieldMapper' is set
      if (formFieldMapper === undefined || formFieldMapper === null) {
        throw new Error("Missing the required parameter 'formFieldMapper' when calling formFieldMapperFormBlueprintUuidFieldUuidPut");
      }

      let pathParams = {
        'form_blueprint_uuid': formBlueprintUuid,
        'field_uuid': fieldUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['admin_jwt'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = FormFieldMapper;
      return this.apiClient.callApi(
        '/form-field-mapper/{form_blueprint_uuid}/{field_uuid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formFieldMapperGet operation.
     * @callback module:api-content-service/controllers/DefaultApi~formFieldMapperGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:api-content-service/models/FormFieldMapper>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all form-field mappings
     * @param {Number} limit Limit of the list
     * @param {Number} offset Offset of the list
     * @param {String} userUuid The UUID of the user
     * @param {module:api-content-service/controllers/DefaultApi~formFieldMapperGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:api-content-service/models/FormFieldMapper>}
     */
    formFieldMapperGet(limit, offset, userUuid, callback) {
      let postBody = null;
      // verify the required parameter 'limit' is set
      if (limit === undefined || limit === null) {
        throw new Error("Missing the required parameter 'limit' when calling formFieldMapperGet");
      }
      // verify the required parameter 'offset' is set
      if (offset === undefined || offset === null) {
        throw new Error("Missing the required parameter 'offset' when calling formFieldMapperGet");
      }
      // verify the required parameter 'userUuid' is set
      if (userUuid === undefined || userUuid === null) {
        throw new Error("Missing the required parameter 'userUuid' when calling formFieldMapperGet");
      }

      let pathParams = {
        'user_uuid': userUuid
      };
      let queryParams = {
        'limit': limit,
        'offset': offset
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['admin_jwt'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [FormFieldMapper];
      return this.apiClient.callApi(
        '/form-field-mapper', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formFieldMapperPost operation.
     * @callback module:api-content-service/controllers/DefaultApi~formFieldMapperPostCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/FormFieldMapper} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a form-field mapping (admin only)
     * @param {module:api-content-service/models/FormFieldMapper} formFieldMapper 
     * @param {module:api-content-service/controllers/DefaultApi~formFieldMapperPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/FormFieldMapper}
     */
    formFieldMapperPost(formFieldMapper, callback) {
      let postBody = formFieldMapper;
      // verify the required parameter 'formFieldMapper' is set
      if (formFieldMapper === undefined || formFieldMapper === null) {
        throw new Error("Missing the required parameter 'formFieldMapper' when calling formFieldMapperPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['admin_jwt'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = FormFieldMapper;
      return this.apiClient.callApi(
        '/form-field-mapper', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formInstancesFormBlueprintUuidUserUuidDelete operation.
     * @callback module:api-content-service/controllers/DefaultApi~formInstancesFormBlueprintUuidUserUuidDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a form instance
     * @param {String} formBlueprintUuid The UUID of the form blueprint
     * @param {String} userUuid The UUID of the user
     * @param {module:api-content-service/controllers/DefaultApi~formInstancesFormBlueprintUuidUserUuidDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    formInstancesFormBlueprintUuidUserUuidDelete(formBlueprintUuid, userUuid, callback) {
      let postBody = null;
      // verify the required parameter 'formBlueprintUuid' is set
      if (formBlueprintUuid === undefined || formBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'formBlueprintUuid' when calling formInstancesFormBlueprintUuidUserUuidDelete");
      }
      // verify the required parameter 'userUuid' is set
      if (userUuid === undefined || userUuid === null) {
        throw new Error("Missing the required parameter 'userUuid' when calling formInstancesFormBlueprintUuidUserUuidDelete");
      }

      let pathParams = {
        'form_blueprint_uuid': formBlueprintUuid,
        'user_uuid': userUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user_jwt'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/form-instances/{form_blueprint_uuid}/{user_uuid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formInstancesFormBlueprintUuidUserUuidGet operation.
     * @callback module:api-content-service/controllers/DefaultApi~formInstancesFormBlueprintUuidUserUuidGetCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/FormDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a user's specific form instance
     * @param {String} formBlueprintUuid The UUID of the form blueprint
     * @param {String} userUuid The UUID of the user
     * @param {module:api-content-service/controllers/DefaultApi~formInstancesFormBlueprintUuidUserUuidGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/FormDTO}
     */
    formInstancesFormBlueprintUuidUserUuidGet(formBlueprintUuid, userUuid, callback) {
      let postBody = null;
      // verify the required parameter 'formBlueprintUuid' is set
      if (formBlueprintUuid === undefined || formBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'formBlueprintUuid' when calling formInstancesFormBlueprintUuidUserUuidGet");
      }
      // verify the required parameter 'userUuid' is set
      if (userUuid === undefined || userUuid === null) {
        throw new Error("Missing the required parameter 'userUuid' when calling formInstancesFormBlueprintUuidUserUuidGet");
      }

      let pathParams = {
        'form_blueprint_uuid': formBlueprintUuid,
        'user_uuid': userUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user_jwt'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = FormDTO;
      return this.apiClient.callApi(
        '/form-instances/{form_blueprint_uuid}/{user_uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formInstancesFormBlueprintUuidUserUuidPut operation.
     * @callback module:api-content-service/controllers/DefaultApi~formInstancesFormBlueprintUuidUserUuidPutCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/FormDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a form instance
     * @param {String} formBlueprintUuid The UUID of the form blueprint
     * @param {String} userUuid The UUID of the user
     * @param {module:api-content-service/models/FormInstance} formInstance 
     * @param {module:api-content-service/controllers/DefaultApi~formInstancesFormBlueprintUuidUserUuidPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/FormDTO}
     */
    formInstancesFormBlueprintUuidUserUuidPut(formBlueprintUuid, userUuid, formInstance, callback) {
      let postBody = formInstance;
      // verify the required parameter 'formBlueprintUuid' is set
      if (formBlueprintUuid === undefined || formBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'formBlueprintUuid' when calling formInstancesFormBlueprintUuidUserUuidPut");
      }
      // verify the required parameter 'userUuid' is set
      if (userUuid === undefined || userUuid === null) {
        throw new Error("Missing the required parameter 'userUuid' when calling formInstancesFormBlueprintUuidUserUuidPut");
      }
      // verify the required parameter 'formInstance' is set
      if (formInstance === undefined || formInstance === null) {
        throw new Error("Missing the required parameter 'formInstance' when calling formInstancesFormBlueprintUuidUserUuidPut");
      }

      let pathParams = {
        'form_blueprint_uuid': formBlueprintUuid,
        'user_uuid': userUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user_jwt'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = FormDTO;
      return this.apiClient.callApi(
        '/form-instances/{form_blueprint_uuid}/{user_uuid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formInstancesGet operation.
     * @callback module:api-content-service/controllers/DefaultApi~formInstancesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:api-content-service/models/FormDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all form instances
     * @param {String} userUuid The UUID of the user
     * @param {Number} limit Limit of the list
     * @param {Number} offset Offset of the list
     * @param {module:api-content-service/controllers/DefaultApi~formInstancesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:api-content-service/models/FormDTO>}
     */
    formInstancesGet(userUuid, limit, offset, callback) {
      let postBody = null;
      // verify the required parameter 'userUuid' is set
      if (userUuid === undefined || userUuid === null) {
        throw new Error("Missing the required parameter 'userUuid' when calling formInstancesGet");
      }
      // verify the required parameter 'limit' is set
      if (limit === undefined || limit === null) {
        throw new Error("Missing the required parameter 'limit' when calling formInstancesGet");
      }
      // verify the required parameter 'offset' is set
      if (offset === undefined || offset === null) {
        throw new Error("Missing the required parameter 'offset' when calling formInstancesGet");
      }

      let pathParams = {
        'user_uuid': userUuid
      };
      let queryParams = {
        'limit': limit,
        'offset': offset
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user_jwt'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [FormDTO];
      return this.apiClient.callApi(
        '/form-instances', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formInstancesPost operation.
     * @callback module:api-content-service/controllers/DefaultApi~formInstancesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/FormDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a form instance (user)
     * @param {module:api-content-service/models/FormInstance} formInstance 
     * @param {module:api-content-service/controllers/DefaultApi~formInstancesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/FormDTO}
     */
    formInstancesPost(formInstance, callback) {
      let postBody = formInstance;
      // verify the required parameter 'formInstance' is set
      if (formInstance === undefined || formInstance === null) {
        throw new Error("Missing the required parameter 'formInstance' when calling formInstancesPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user_jwt'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = FormDTO;
      return this.apiClient.callApi(
        '/form-instances', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formsFormBlueprintUuidDelete operation.
     * @callback module:api-content-service/controllers/DefaultApi~formsFormBlueprintUuidDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete form template (admin only)
     * @param {String} formBlueprintUuid The UUID of the form blueprint
     * @param {module:api-content-service/controllers/DefaultApi~formsFormBlueprintUuidDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    formsFormBlueprintUuidDelete(formBlueprintUuid, callback) {
      let postBody = null;
      // verify the required parameter 'formBlueprintUuid' is set
      if (formBlueprintUuid === undefined || formBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'formBlueprintUuid' when calling formsFormBlueprintUuidDelete");
      }

      let pathParams = {
        'form_blueprint_uuid': formBlueprintUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['admin_jwt'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/forms/{form_blueprint_uuid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formsFormBlueprintUuidGet operation.
     * @callback module:api-content-service/controllers/DefaultApi~formsFormBlueprintUuidGetCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/FormBlueprint} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get form template
     * @param {String} formBlueprintUuid The UUID of the form blueprint
     * @param {module:api-content-service/controllers/DefaultApi~formsFormBlueprintUuidGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/FormBlueprint}
     */
    formsFormBlueprintUuidGet(formBlueprintUuid, callback) {
      let postBody = null;
      // verify the required parameter 'formBlueprintUuid' is set
      if (formBlueprintUuid === undefined || formBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'formBlueprintUuid' when calling formsFormBlueprintUuidGet");
      }

      let pathParams = {
        'form_blueprint_uuid': formBlueprintUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = FormBlueprint;
      return this.apiClient.callApi(
        '/forms/{form_blueprint_uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formsFormBlueprintUuidPut operation.
     * @callback module:api-content-service/controllers/DefaultApi~formsFormBlueprintUuidPutCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/FormBlueprint} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update form template (admin only)
     * @param {String} formBlueprintUuid The UUID of the form blueprint
     * @param {module:api-content-service/models/FormBlueprint} formBlueprint 
     * @param {module:api-content-service/controllers/DefaultApi~formsFormBlueprintUuidPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/FormBlueprint}
     */
    formsFormBlueprintUuidPut(formBlueprintUuid, formBlueprint, callback) {
      let postBody = formBlueprint;
      // verify the required parameter 'formBlueprintUuid' is set
      if (formBlueprintUuid === undefined || formBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'formBlueprintUuid' when calling formsFormBlueprintUuidPut");
      }
      // verify the required parameter 'formBlueprint' is set
      if (formBlueprint === undefined || formBlueprint === null) {
        throw new Error("Missing the required parameter 'formBlueprint' when calling formsFormBlueprintUuidPut");
      }

      let pathParams = {
        'form_blueprint_uuid': formBlueprintUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['admin_jwt'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = FormBlueprint;
      return this.apiClient.callApi(
        '/forms/{form_blueprint_uuid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formsGet operation.
     * @callback module:api-content-service/controllers/DefaultApi~formsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:api-content-service/models/FormBlueprint>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List form templates
     * @param {Number} limit Limit of the list
     * @param {Number} offset Offset of the list
     * @param {module:api-content-service/controllers/DefaultApi~formsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:api-content-service/models/FormBlueprint>}
     */
    formsGet(limit, offset, callback) {
      let postBody = null;
      // verify the required parameter 'limit' is set
      if (limit === undefined || limit === null) {
        throw new Error("Missing the required parameter 'limit' when calling formsGet");
      }
      // verify the required parameter 'offset' is set
      if (offset === undefined || offset === null) {
        throw new Error("Missing the required parameter 'offset' when calling formsGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'limit': limit,
        'offset': offset
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [FormBlueprint];
      return this.apiClient.callApi(
        '/forms', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the formsPost operation.
     * @callback module:api-content-service/controllers/DefaultApi~formsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/FormBlueprint} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create form template (admin only)
     * @param {module:api-content-service/models/FormBlueprint} formBlueprint 
     * @param {module:api-content-service/controllers/DefaultApi~formsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/FormBlueprint}
     */
    formsPost(formBlueprint, callback) {
      let postBody = formBlueprint;
      // verify the required parameter 'formBlueprint' is set
      if (formBlueprint === undefined || formBlueprint === null) {
        throw new Error("Missing the required parameter 'formBlueprint' when calling formsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['admin_jwt'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = FormBlueprint;
      return this.apiClient.callApi(
        '/forms', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the mediaGet operation.
     * @callback module:api-content-service/controllers/DefaultApi~mediaGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:api-content-service/models/Media>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * (Optional) List media items
     * @param {Number} limit Limit of the list
     * @param {Number} offset Offset of the list
     * @param {module:api-content-service/controllers/DefaultApi~mediaGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:api-content-service/models/Media>}
     */
    mediaGet(limit, offset, callback) {
      let postBody = null;
      // verify the required parameter 'limit' is set
      if (limit === undefined || limit === null) {
        throw new Error("Missing the required parameter 'limit' when calling mediaGet");
      }
      // verify the required parameter 'offset' is set
      if (offset === undefined || offset === null) {
        throw new Error("Missing the required parameter 'offset' when calling mediaGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'limit': limit,
        'offset': offset
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Media];
      return this.apiClient.callApi(
        '/media', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the mediaMediaUuidDelete operation.
     * @callback module:api-content-service/controllers/DefaultApi~mediaMediaUuidDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete media (admin only)
     * @param {String} mediaUuid The UUID of the media resource
     * @param {module:api-content-service/controllers/DefaultApi~mediaMediaUuidDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    mediaMediaUuidDelete(mediaUuid, callback) {
      let postBody = null;
      // verify the required parameter 'mediaUuid' is set
      if (mediaUuid === undefined || mediaUuid === null) {
        throw new Error("Missing the required parameter 'mediaUuid' when calling mediaMediaUuidDelete");
      }

      let pathParams = {
        'media_uuid': mediaUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['admin_jwt'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/media/{media_uuid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the mediaMediaUuidGet operation.
     * @callback module:api-content-service/controllers/DefaultApi~mediaMediaUuidGetCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/Media} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get media metadata
     * @param {String} mediaUuid The UUID of the media resource
     * @param {module:api-content-service/controllers/DefaultApi~mediaMediaUuidGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/Media}
     */
    mediaMediaUuidGet(mediaUuid, callback) {
      let postBody = null;
      // verify the required parameter 'mediaUuid' is set
      if (mediaUuid === undefined || mediaUuid === null) {
        throw new Error("Missing the required parameter 'mediaUuid' when calling mediaMediaUuidGet");
      }

      let pathParams = {
        'media_uuid': mediaUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Media;
      return this.apiClient.callApi(
        '/media/{media_uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the mediaMediaUuidPut operation.
     * @callback module:api-content-service/controllers/DefaultApi~mediaMediaUuidPutCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/Media} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update media metadata (admin only)
     * @param {String} mediaUuid The UUID of the media resource
     * @param {module:api-content-service/models/Media} media 
     * @param {module:api-content-service/controllers/DefaultApi~mediaMediaUuidPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/Media}
     */
    mediaMediaUuidPut(mediaUuid, media, callback) {
      let postBody = media;
      // verify the required parameter 'mediaUuid' is set
      if (mediaUuid === undefined || mediaUuid === null) {
        throw new Error("Missing the required parameter 'mediaUuid' when calling mediaMediaUuidPut");
      }
      // verify the required parameter 'media' is set
      if (media === undefined || media === null) {
        throw new Error("Missing the required parameter 'media' when calling mediaMediaUuidPut");
      }

      let pathParams = {
        'media_uuid': mediaUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['admin_jwt'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Media;
      return this.apiClient.callApi(
        '/media/{media_uuid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the mediaPostMultipart operation.
     * @callback module:api-content-service/controllers/DefaultApi~mediaPostMultipartCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/Media} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Upload new media (admin only)
     * @param {File} file The file to upload
     * @param {Object} opts Optional parameters
     * @param {String} [description] Media description
     * @param {String} [type] Media type (e.g. video, image, etc.)
     * @param {String} [title] Media title
     * @param {module:api-content-service/controllers/DefaultApi~mediaPostMultipartCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/Media}
     */
    mediaPostMultipart(file, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling mediaPostMultipart");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'file': file,
        'description': opts['description'],
        'type': opts['type'],
        'title': opts['title']
      };

      let authNames = ['admin_jwt'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Media;
      return this.apiClient.callApi(
        '/media', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the taskInstancesGet operation.
     * @callback module:api-content-service/controllers/DefaultApi~taskInstancesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:api-content-service/models/TaskDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all task instances
     * @param {String} userUuid The UUID of the user
     * @param {Number} limit Limit of the list
     * @param {Number} offset Offset of the list
     * @param {module:api-content-service/controllers/DefaultApi~taskInstancesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:api-content-service/models/TaskDTO>}
     */
    taskInstancesGet(userUuid, limit, offset, callback) {
      let postBody = null;
      // verify the required parameter 'userUuid' is set
      if (userUuid === undefined || userUuid === null) {
        throw new Error("Missing the required parameter 'userUuid' when calling taskInstancesGet");
      }
      // verify the required parameter 'limit' is set
      if (limit === undefined || limit === null) {
        throw new Error("Missing the required parameter 'limit' when calling taskInstancesGet");
      }
      // verify the required parameter 'offset' is set
      if (offset === undefined || offset === null) {
        throw new Error("Missing the required parameter 'offset' when calling taskInstancesGet");
      }

      let pathParams = {
        'user_uuid': userUuid
      };
      let queryParams = {
        'limit': limit,
        'offset': offset
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user_jwt'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [TaskDTO];
      return this.apiClient.callApi(
        '/task-instances', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the taskInstancesPost operation.
     * @callback module:api-content-service/controllers/DefaultApi~taskInstancesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/TaskDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new task instance
     * @param {module:api-content-service/models/TaskInstance} taskInstance 
     * @param {module:api-content-service/controllers/DefaultApi~taskInstancesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/TaskDTO}
     */
    taskInstancesPost(taskInstance, callback) {
      let postBody = taskInstance;
      // verify the required parameter 'taskInstance' is set
      if (taskInstance === undefined || taskInstance === null) {
        throw new Error("Missing the required parameter 'taskInstance' when calling taskInstancesPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user_jwt'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaskDTO;
      return this.apiClient.callApi(
        '/task-instances', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the taskInstancesTaskBlueprintUuidUserUuidDelete operation.
     * @callback module:api-content-service/controllers/DefaultApi~taskInstancesTaskBlueprintUuidUserUuidDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a task instance
     * @param {String} taskBlueprintUuid The UUID of the task blueprint
     * @param {String} userUuid The UUID of the user
     * @param {module:api-content-service/controllers/DefaultApi~taskInstancesTaskBlueprintUuidUserUuidDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    taskInstancesTaskBlueprintUuidUserUuidDelete(taskBlueprintUuid, userUuid, callback) {
      let postBody = null;
      // verify the required parameter 'taskBlueprintUuid' is set
      if (taskBlueprintUuid === undefined || taskBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'taskBlueprintUuid' when calling taskInstancesTaskBlueprintUuidUserUuidDelete");
      }
      // verify the required parameter 'userUuid' is set
      if (userUuid === undefined || userUuid === null) {
        throw new Error("Missing the required parameter 'userUuid' when calling taskInstancesTaskBlueprintUuidUserUuidDelete");
      }

      let pathParams = {
        'task_blueprint_uuid': taskBlueprintUuid,
        'user_uuid': userUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user_jwt'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/task-instances/{task_blueprint_uuid}/{user_uuid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the taskInstancesTaskBlueprintUuidUserUuidGet operation.
     * @callback module:api-content-service/controllers/DefaultApi~taskInstancesTaskBlueprintUuidUserUuidGetCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/TaskDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a user's specific task instance
     * @param {String} taskBlueprintUuid The UUID of the task blueprint
     * @param {String} userUuid The UUID of the user
     * @param {module:api-content-service/controllers/DefaultApi~taskInstancesTaskBlueprintUuidUserUuidGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/TaskDTO}
     */
    taskInstancesTaskBlueprintUuidUserUuidGet(taskBlueprintUuid, userUuid, callback) {
      let postBody = null;
      // verify the required parameter 'taskBlueprintUuid' is set
      if (taskBlueprintUuid === undefined || taskBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'taskBlueprintUuid' when calling taskInstancesTaskBlueprintUuidUserUuidGet");
      }
      // verify the required parameter 'userUuid' is set
      if (userUuid === undefined || userUuid === null) {
        throw new Error("Missing the required parameter 'userUuid' when calling taskInstancesTaskBlueprintUuidUserUuidGet");
      }

      let pathParams = {
        'task_blueprint_uuid': taskBlueprintUuid,
        'user_uuid': userUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user_jwt'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaskDTO;
      return this.apiClient.callApi(
        '/task-instances/{task_blueprint_uuid}/{user_uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the taskInstancesTaskBlueprintUuidUserUuidPut operation.
     * @callback module:api-content-service/controllers/DefaultApi~taskInstancesTaskBlueprintUuidUserUuidPutCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/TaskDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a task instance
     * @param {String} taskBlueprintUuid The UUID of the task blueprint
     * @param {String} userUuid The UUID of the user
     * @param {module:api-content-service/models/TaskInstance} taskInstance 
     * @param {module:api-content-service/controllers/DefaultApi~taskInstancesTaskBlueprintUuidUserUuidPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/TaskDTO}
     */
    taskInstancesTaskBlueprintUuidUserUuidPut(taskBlueprintUuid, userUuid, taskInstance, callback) {
      let postBody = taskInstance;
      // verify the required parameter 'taskBlueprintUuid' is set
      if (taskBlueprintUuid === undefined || taskBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'taskBlueprintUuid' when calling taskInstancesTaskBlueprintUuidUserUuidPut");
      }
      // verify the required parameter 'userUuid' is set
      if (userUuid === undefined || userUuid === null) {
        throw new Error("Missing the required parameter 'userUuid' when calling taskInstancesTaskBlueprintUuidUserUuidPut");
      }
      // verify the required parameter 'taskInstance' is set
      if (taskInstance === undefined || taskInstance === null) {
        throw new Error("Missing the required parameter 'taskInstance' when calling taskInstancesTaskBlueprintUuidUserUuidPut");
      }

      let pathParams = {
        'task_blueprint_uuid': taskBlueprintUuid,
        'user_uuid': userUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user_jwt'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaskDTO;
      return this.apiClient.callApi(
        '/task-instances/{task_blueprint_uuid}/{user_uuid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the tasksGet operation.
     * @callback module:api-content-service/controllers/DefaultApi~tasksGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:api-content-service/models/TaskBlueprint>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List task templates
     * @param {Number} limit Limit of the list
     * @param {Number} offset Offset of the list
     * @param {module:api-content-service/controllers/DefaultApi~tasksGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:api-content-service/models/TaskBlueprint>}
     */
    tasksGet(limit, offset, callback) {
      let postBody = null;
      // verify the required parameter 'limit' is set
      if (limit === undefined || limit === null) {
        throw new Error("Missing the required parameter 'limit' when calling tasksGet");
      }
      // verify the required parameter 'offset' is set
      if (offset === undefined || offset === null) {
        throw new Error("Missing the required parameter 'offset' when calling tasksGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'limit': limit,
        'offset': offset
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [TaskBlueprint];
      return this.apiClient.callApi(
        '/tasks', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the tasksPost operation.
     * @callback module:api-content-service/controllers/DefaultApi~tasksPostCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/TaskBlueprint} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create task template (admin only)
     * @param {module:api-content-service/models/TaskBlueprint} taskBlueprint 
     * @param {module:api-content-service/controllers/DefaultApi~tasksPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/TaskBlueprint}
     */
    tasksPost(taskBlueprint, callback) {
      let postBody = taskBlueprint;
      // verify the required parameter 'taskBlueprint' is set
      if (taskBlueprint === undefined || taskBlueprint === null) {
        throw new Error("Missing the required parameter 'taskBlueprint' when calling tasksPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['admin_jwt'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaskBlueprint;
      return this.apiClient.callApi(
        '/tasks', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the tasksTaskBlueprintUuidDelete operation.
     * @callback module:api-content-service/controllers/DefaultApi~tasksTaskBlueprintUuidDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete task template (admin only)
     * @param {String} taskBlueprintUuid The UUID of the task blueprint
     * @param {module:api-content-service/controllers/DefaultApi~tasksTaskBlueprintUuidDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    tasksTaskBlueprintUuidDelete(taskBlueprintUuid, callback) {
      let postBody = null;
      // verify the required parameter 'taskBlueprintUuid' is set
      if (taskBlueprintUuid === undefined || taskBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'taskBlueprintUuid' when calling tasksTaskBlueprintUuidDelete");
      }

      let pathParams = {
        'task_blueprint_uuid': taskBlueprintUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['admin_jwt'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/tasks/{task_blueprint_uuid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the tasksTaskBlueprintUuidGet operation.
     * @callback module:api-content-service/controllers/DefaultApi~tasksTaskBlueprintUuidGetCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/TaskBlueprint} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get task template
     * @param {String} taskBlueprintUuid The UUID of the task blueprint
     * @param {module:api-content-service/controllers/DefaultApi~tasksTaskBlueprintUuidGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/TaskBlueprint}
     */
    tasksTaskBlueprintUuidGet(taskBlueprintUuid, callback) {
      let postBody = null;
      // verify the required parameter 'taskBlueprintUuid' is set
      if (taskBlueprintUuid === undefined || taskBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'taskBlueprintUuid' when calling tasksTaskBlueprintUuidGet");
      }

      let pathParams = {
        'task_blueprint_uuid': taskBlueprintUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaskBlueprint;
      return this.apiClient.callApi(
        '/tasks/{task_blueprint_uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the tasksTaskBlueprintUuidPut operation.
     * @callback module:api-content-service/controllers/DefaultApi~tasksTaskBlueprintUuidPutCallback
     * @param {String} error Error message, if any.
     * @param {module:api-content-service/models/TaskBlueprint} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update task template (admin only)
     * @param {String} taskBlueprintUuid The UUID of the task blueprint
     * @param {module:api-content-service/models/TaskBlueprint} taskBlueprint 
     * @param {module:api-content-service/controllers/DefaultApi~tasksTaskBlueprintUuidPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:api-content-service/models/TaskBlueprint}
     */
    tasksTaskBlueprintUuidPut(taskBlueprintUuid, taskBlueprint, callback) {
      let postBody = taskBlueprint;
      // verify the required parameter 'taskBlueprintUuid' is set
      if (taskBlueprintUuid === undefined || taskBlueprintUuid === null) {
        throw new Error("Missing the required parameter 'taskBlueprintUuid' when calling tasksTaskBlueprintUuidPut");
      }
      // verify the required parameter 'taskBlueprint' is set
      if (taskBlueprint === undefined || taskBlueprint === null) {
        throw new Error("Missing the required parameter 'taskBlueprint' when calling tasksTaskBlueprintUuidPut");
      }

      let pathParams = {
        'task_blueprint_uuid': taskBlueprintUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['admin_jwt'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaskBlueprint;
      return this.apiClient.callApi(
        '/tasks/{task_blueprint_uuid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
