/* tslint:disable */
/* eslint-disable */
/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Composite ID for FormInstance
 * @export
 * @interface FormInstanceId
 */
export interface FormInstanceId {
    /**
     * UUID for a Form Blueprint
     * @type {string}
     * @memberof FormInstanceId
     */
    formBlueprintUuid: string;
    /**
     * UUID for a User
     * @type {string}
     * @memberof FormInstanceId
     */
    userUuid: string;
}

/**
 * Check if a given object implements the FormInstanceId interface.
 */
export function instanceOfFormInstanceId(value: object): value is FormInstanceId {
    if (!('formBlueprintUuid' in value) || value['formBlueprintUuid'] === undefined) return false;
    if (!('userUuid' in value) || value['userUuid'] === undefined) return false;
    return true;
}

export function FormInstanceIdFromJSON(json: any): FormInstanceId {
    return FormInstanceIdFromJSONTyped(json, false);
}

export function FormInstanceIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormInstanceId {
    if (json == null) {
        return json;
    }
    return {
        
        'formBlueprintUuid': json['form_blueprint_uuid'],
        'userUuid': json['user_uuid'],
    };
}

export function FormInstanceIdToJSON(json: any): FormInstanceId {
    return FormInstanceIdToJSONTyped(json, false);
}

export function FormInstanceIdToJSONTyped(value?: FormInstanceId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'form_blueprint_uuid': value['formBlueprintUuid'],
        'user_uuid': value['userUuid'],
    };
}

