/* tslint:disable */
/* eslint-disable */
/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FormBlueprint
 */
export interface FormBlueprint {
    /**
     * UUID for a Form Blueprint
     * @type {string}
     * @memberof FormBlueprint
     */
    formBlueprintUuid: string;
    /**
     * 
     * @type {string}
     * @memberof FormBlueprint
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof FormBlueprint
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof FormBlueprint
     */
    callbackUrl?: string;
}

/**
 * Check if a given object implements the FormBlueprint interface.
 */
export function instanceOfFormBlueprint(value: object): value is FormBlueprint {
    if (!('formBlueprintUuid' in value) || value['formBlueprintUuid'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function FormBlueprintFromJSON(json: any): FormBlueprint {
    return FormBlueprintFromJSONTyped(json, false);
}

export function FormBlueprintFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormBlueprint {
    if (json == null) {
        return json;
    }
    return {
        
        'formBlueprintUuid': json['form_blueprint_uuid'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'callbackUrl': json['callback_url'] == null ? undefined : json['callback_url'],
    };
}

export function FormBlueprintToJSON(json: any): FormBlueprint {
    return FormBlueprintToJSONTyped(json, false);
}

export function FormBlueprintToJSONTyped(value?: FormBlueprint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'form_blueprint_uuid': value['formBlueprintUuid'],
        'title': value['title'],
        'description': value['description'],
        'callback_url': value['callbackUrl'],
    };
}

