/* tslint:disable */
/* eslint-disable */
/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskInstanceId } from './TaskInstanceId';
import {
    TaskInstanceIdFromJSON,
    TaskInstanceIdFromJSONTyped,
    TaskInstanceIdToJSON,
    TaskInstanceIdToJSONTyped,
} from './TaskInstanceId';

/**
 * User's progress for a specific task
 * @export
 * @interface TaskInstance
 */
export interface TaskInstance {
    /**
     * 
     * @type {TaskInstanceId}
     * @memberof TaskInstance
     */
    id: TaskInstanceId;
    /**
     * True if completed, false otherwise
     * @type {boolean}
     * @memberof TaskInstance
     */
    status: boolean;
}

/**
 * Check if a given object implements the TaskInstance interface.
 */
export function instanceOfTaskInstance(value: object): value is TaskInstance {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TaskInstanceFromJSON(json: any): TaskInstance {
    return TaskInstanceFromJSONTyped(json, false);
}

export function TaskInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'id': TaskInstanceIdFromJSON(json['id']),
        'status': json['status'],
    };
}

export function TaskInstanceToJSON(json: any): TaskInstance {
    return TaskInstanceToJSONTyped(json, false);
}

export function TaskInstanceToJSONTyped(value?: TaskInstance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': TaskInstanceIdToJSON(value['id']),
        'status': value['status'],
    };
}

