/* tslint:disable */
/* eslint-disable */
/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskBlueprint
 */
export interface TaskBlueprint {
    /**
     * UUID for a Task Blueprint
     * @type {string}
     * @memberof TaskBlueprint
     */
    taskBlueprintUuid: string;
    /**
     * 
     * @type {string}
     * @memberof TaskBlueprint
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TaskBlueprint
     */
    description?: string;
}

/**
 * Check if a given object implements the TaskBlueprint interface.
 */
export function instanceOfTaskBlueprint(value: object): value is TaskBlueprint {
    if (!('taskBlueprintUuid' in value) || value['taskBlueprintUuid'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TaskBlueprintFromJSON(json: any): TaskBlueprint {
    return TaskBlueprintFromJSONTyped(json, false);
}

export function TaskBlueprintFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskBlueprint {
    if (json == null) {
        return json;
    }
    return {
        
        'taskBlueprintUuid': json['task_blueprint_uuid'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function TaskBlueprintToJSON(json: any): TaskBlueprint {
    return TaskBlueprintToJSONTyped(json, false);
}

export function TaskBlueprintToJSONTyped(value?: TaskBlueprint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task_blueprint_uuid': value['taskBlueprintUuid'],
        'title': value['title'],
        'description': value['description'],
    };
}

