/* tslint:disable */
/* eslint-disable */
/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Composite ID for DayComponentsMapper
 * @export
 * @interface DayComponentsMapperId
 */
export interface DayComponentsMapperId {
    /**
     * UUID for a Day Blueprint
     * @type {string}
     * @memberof DayComponentsMapperId
     */
    dayBlueprintUuid: string;
    /**
     * UUID for a Day Component
     * @type {string}
     * @memberof DayComponentsMapperId
     */
    componentUuid: string;
}

/**
 * Check if a given object implements the DayComponentsMapperId interface.
 */
export function instanceOfDayComponentsMapperId(value: object): value is DayComponentsMapperId {
    if (!('dayBlueprintUuid' in value) || value['dayBlueprintUuid'] === undefined) return false;
    if (!('componentUuid' in value) || value['componentUuid'] === undefined) return false;
    return true;
}

export function DayComponentsMapperIdFromJSON(json: any): DayComponentsMapperId {
    return DayComponentsMapperIdFromJSONTyped(json, false);
}

export function DayComponentsMapperIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayComponentsMapperId {
    if (json == null) {
        return json;
    }
    return {
        
        'dayBlueprintUuid': json['day_blueprint_uuid'],
        'componentUuid': json['component_uuid'],
    };
}

export function DayComponentsMapperIdToJSON(json: any): DayComponentsMapperId {
    return DayComponentsMapperIdToJSONTyped(json, false);
}

export function DayComponentsMapperIdToJSONTyped(value?: DayComponentsMapperId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day_blueprint_uuid': value['dayBlueprintUuid'],
        'component_uuid': value['componentUuid'],
    };
}

