/* tslint:disable */
/* eslint-disable */
/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DayInstanceId } from './DayInstanceId';
import {
    DayInstanceIdFromJSON,
    DayInstanceIdFromJSONTyped,
    DayInstanceIdToJSON,
    DayInstanceIdToJSONTyped,
} from './DayInstanceId';

/**
 * Specific instance of a day for a user
 * @export
 * @interface DayInstance
 */
export interface DayInstance {
    /**
     * 
     * @type {DayInstanceId}
     * @memberof DayInstance
     */
    id: DayInstanceId;
    /**
     * 
     * @type {string}
     * @memberof DayInstance
     */
    status: DayInstanceStatusEnum;
}


/**
 * @export
 */
export const DayInstanceStatusEnum = {
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED',
    NotStarted: 'NOT_STARTED'
} as const;
export type DayInstanceStatusEnum = typeof DayInstanceStatusEnum[keyof typeof DayInstanceStatusEnum];


/**
 * Check if a given object implements the DayInstance interface.
 */
export function instanceOfDayInstance(value: object): value is DayInstance {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DayInstanceFromJSON(json: any): DayInstance {
    return DayInstanceFromJSONTyped(json, false);
}

export function DayInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'id': DayInstanceIdFromJSON(json['id']),
        'status': json['status'],
    };
}

export function DayInstanceToJSON(json: any): DayInstance {
    return DayInstanceToJSONTyped(json, false);
}

export function DayInstanceToJSONTyped(value?: DayInstance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': DayInstanceIdToJSON(value['id']),
        'status': value['status'],
    };
}

