/* tslint:disable */
/* eslint-disable */
/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Composite ID for DayInstance
 * @export
 * @interface DayInstanceId
 */
export interface DayInstanceId {
    /**
     * UUID for a Day Blueprint
     * @type {string}
     * @memberof DayInstanceId
     */
    dayBlueprintUuid: string;
    /**
     * UUID for a User
     * @type {string}
     * @memberof DayInstanceId
     */
    userUuid: string;
}

/**
 * Check if a given object implements the DayInstanceId interface.
 */
export function instanceOfDayInstanceId(value: object): value is DayInstanceId {
    if (!('dayBlueprintUuid' in value) || value['dayBlueprintUuid'] === undefined) return false;
    if (!('userUuid' in value) || value['userUuid'] === undefined) return false;
    return true;
}

export function DayInstanceIdFromJSON(json: any): DayInstanceId {
    return DayInstanceIdFromJSONTyped(json, false);
}

export function DayInstanceIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayInstanceId {
    if (json == null) {
        return json;
    }
    return {
        
        'dayBlueprintUuid': json['day_blueprint_uuid'],
        'userUuid': json['user_uuid'],
    };
}

export function DayInstanceIdToJSON(json: any): DayInstanceId {
    return DayInstanceIdToJSONTyped(json, false);
}

export function DayInstanceIdToJSONTyped(value?: DayInstanceId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day_blueprint_uuid': value['dayBlueprintUuid'],
        'user_uuid': value['userUuid'],
    };
}

