/* tslint:disable */
/* eslint-disable */
/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Composite ID for Members
 * @export
 * @interface MembersId
 */
export interface MembersId {
    /**
     * UUID for a Project Blueprint
     * @type {string}
     * @memberof MembersId
     */
    projectBlueprintUuid: string;
    /**
     * UUID for a User
     * @type {string}
     * @memberof MembersId
     */
    userUuid: string;
}

/**
 * Check if a given object implements the MembersId interface.
 */
export function instanceOfMembersId(value: object): value is MembersId {
    if (!('projectBlueprintUuid' in value) || value['projectBlueprintUuid'] === undefined) return false;
    if (!('userUuid' in value) || value['userUuid'] === undefined) return false;
    return true;
}

export function MembersIdFromJSON(json: any): MembersId {
    return MembersIdFromJSONTyped(json, false);
}

export function MembersIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): MembersId {
    if (json == null) {
        return json;
    }
    return {
        
        'projectBlueprintUuid': json['project_blueprint_uuid'],
        'userUuid': json['user_uuid'],
    };
}

export function MembersIdToJSON(json: any): MembersId {
    return MembersIdToJSONTyped(json, false);
}

export function MembersIdToJSONTyped(value?: MembersId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_blueprint_uuid': value['projectBlueprintUuid'],
        'user_uuid': value['userUuid'],
    };
}

