/* tslint:disable */
/* eslint-disable */
/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Composite ID for ProjectDaysMapper
 * @export
 * @interface ProjectDaysMapperId
 */
export interface ProjectDaysMapperId {
    /**
     * UUID for a Project Blueprint
     * @type {string}
     * @memberof ProjectDaysMapperId
     */
    projectBlueprintUuid: string;
    /**
     * UUID for a Day Blueprint
     * @type {string}
     * @memberof ProjectDaysMapperId
     */
    dayBlueprintUuid: string;
}

/**
 * Check if a given object implements the ProjectDaysMapperId interface.
 */
export function instanceOfProjectDaysMapperId(value: object): value is ProjectDaysMapperId {
    if (!('projectBlueprintUuid' in value) || value['projectBlueprintUuid'] === undefined) return false;
    if (!('dayBlueprintUuid' in value) || value['dayBlueprintUuid'] === undefined) return false;
    return true;
}

export function ProjectDaysMapperIdFromJSON(json: any): ProjectDaysMapperId {
    return ProjectDaysMapperIdFromJSONTyped(json, false);
}

export function ProjectDaysMapperIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDaysMapperId {
    if (json == null) {
        return json;
    }
    return {
        
        'projectBlueprintUuid': json['project_blueprint_uuid'],
        'dayBlueprintUuid': json['day_blueprint_uuid'],
    };
}

export function ProjectDaysMapperIdToJSON(json: any): ProjectDaysMapperId {
    return ProjectDaysMapperIdToJSONTyped(json, false);
}

export function ProjectDaysMapperIdToJSONTyped(value?: ProjectDaysMapperId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_blueprint_uuid': value['projectBlueprintUuid'],
        'day_blueprint_uuid': value['dayBlueprintUuid'],
    };
}

