/* tslint:disable */
/* eslint-disable */
/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Composite ID for ProjectInstance
 * @export
 * @interface ProjectInstanceId
 */
export interface ProjectInstanceId {
    /**
     * UUID for a Project Blueprint
     * @type {string}
     * @memberof ProjectInstanceId
     */
    projectBlueprintUuid: string;
    /**
     * UUID for a User
     * @type {string}
     * @memberof ProjectInstanceId
     */
    userUuid: string;
}

/**
 * Check if a given object implements the ProjectInstanceId interface.
 */
export function instanceOfProjectInstanceId(value: object): value is ProjectInstanceId {
    if (!('projectBlueprintUuid' in value) || value['projectBlueprintUuid'] === undefined) return false;
    if (!('userUuid' in value) || value['userUuid'] === undefined) return false;
    return true;
}

export function ProjectInstanceIdFromJSON(json: any): ProjectInstanceId {
    return ProjectInstanceIdFromJSONTyped(json, false);
}

export function ProjectInstanceIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectInstanceId {
    if (json == null) {
        return json;
    }
    return {
        
        'projectBlueprintUuid': json['project_blueprint_uuid'],
        'userUuid': json['user_uuid'],
    };
}

export function ProjectInstanceIdToJSON(json: any): ProjectInstanceId {
    return ProjectInstanceIdToJSONTyped(json, false);
}

export function ProjectInstanceIdToJSONTyped(value?: ProjectInstanceId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_blueprint_uuid': value['projectBlueprintUuid'],
        'user_uuid': value['userUuid'],
    };
}

