/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DayBlueprint from './models/DayBlueprint';
import DayComponentsMapper from './models/DayComponentsMapper';
import DayComponentsMapperId from './models/DayComponentsMapperId';
import DayDTO from './models/DayDTO';
import DayInstance from './models/DayInstance';
import DayInstanceId from './models/DayInstanceId';
import Error from './models/Error';
import Finances from './models/Finances';
import FinancesId from './models/FinancesId';
import Members from './models/Members';
import MembersId from './models/MembersId';
import ProjectBlueprint from './models/ProjectBlueprint';
import ProjectDTO from './models/ProjectDTO';
import ProjectDaysMapper from './models/ProjectDaysMapper';
import ProjectDaysMapperId from './models/ProjectDaysMapperId';
import ProjectInstance from './models/ProjectInstance';
import ProjectInstanceId from './models/ProjectInstanceId';
import DefaultApi from './controllers/DefaultApi';


/**
* An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ProjectDayApi = require('api-course-service/index'); // See note below*.
* var xxxSvc = new ProjectDayApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ProjectDayApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['api-course-service/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ProjectDayApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ProjectDayApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module api-course-service/index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:api-course-service/ApiClient}
     */
    ApiClient,

    /**
     * The DayBlueprint model constructor.
     * @property {module:api-course-service/models/DayBlueprint}
     */
    DayBlueprint,

    /**
     * The DayComponentsMapper model constructor.
     * @property {module:api-course-service/models/DayComponentsMapper}
     */
    DayComponentsMapper,

    /**
     * The DayComponentsMapperId model constructor.
     * @property {module:api-course-service/models/DayComponentsMapperId}
     */
    DayComponentsMapperId,

    /**
     * The DayDTO model constructor.
     * @property {module:api-course-service/models/DayDTO}
     */
    DayDTO,

    /**
     * The DayInstance model constructor.
     * @property {module:api-course-service/models/DayInstance}
     */
    DayInstance,

    /**
     * The DayInstanceId model constructor.
     * @property {module:api-course-service/models/DayInstanceId}
     */
    DayInstanceId,

    /**
     * The Error model constructor.
     * @property {module:api-course-service/models/Error}
     */
    Error,

    /**
     * The Finances model constructor.
     * @property {module:api-course-service/models/Finances}
     */
    Finances,

    /**
     * The FinancesId model constructor.
     * @property {module:api-course-service/models/FinancesId}
     */
    FinancesId,

    /**
     * The Members model constructor.
     * @property {module:api-course-service/models/Members}
     */
    Members,

    /**
     * The MembersId model constructor.
     * @property {module:api-course-service/models/MembersId}
     */
    MembersId,

    /**
     * The ProjectBlueprint model constructor.
     * @property {module:api-course-service/models/ProjectBlueprint}
     */
    ProjectBlueprint,

    /**
     * The ProjectDTO model constructor.
     * @property {module:api-course-service/models/ProjectDTO}
     */
    ProjectDTO,

    /**
     * The ProjectDaysMapper model constructor.
     * @property {module:api-course-service/models/ProjectDaysMapper}
     */
    ProjectDaysMapper,

    /**
     * The ProjectDaysMapperId model constructor.
     * @property {module:api-course-service/models/ProjectDaysMapperId}
     */
    ProjectDaysMapperId,

    /**
     * The ProjectInstance model constructor.
     * @property {module:api-course-service/models/ProjectInstance}
     */
    ProjectInstance,

    /**
     * The ProjectInstanceId model constructor.
     * @property {module:api-course-service/models/ProjectInstanceId}
     */
    ProjectInstanceId,

    /**
    * The DefaultApi service constructor.
    * @property {module:api-course-service/controllers/DefaultApi}
    */
    DefaultApi
};
