/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DayInstanceId from './DayInstanceId';

/**
 * The DayInstance model module.
 * @module openapi/models/DayInstance
 * @version 1.0.0
 */
class DayInstance {
    /**
     * Constructs a new <code>DayInstance</code>.
     * Specific instance of a day for a user
     * @alias module:openapi/models/DayInstance
     * @param id {module:openapi/models/DayInstanceId} 
     * @param status {module:openapi/models/DayInstance.StatusEnum} 
     */
    constructor(id, status) { 
        
        DayInstance.initialize(this, id, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, status) { 
        obj['id'] = id;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>DayInstance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:openapi/models/DayInstance} obj Optional instance to populate.
     * @return {module:openapi/models/DayInstance} The populated <code>DayInstance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DayInstance();

            if (data.hasOwnProperty('id')) {
                obj['id'] = DayInstanceId.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DayInstance</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DayInstance</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DayInstance.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `id`
        if (data['id']) { // data not null
          DayInstanceId.validateJSON(data['id']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

DayInstance.RequiredProperties = ["id", "status"];

/**
 * @member {module:openapi/models/DayInstanceId} id
 */
DayInstance.prototype['id'] = undefined;

/**
 * @member {module:openapi/models/DayInstance.StatusEnum} status
 */
DayInstance.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
DayInstance['StatusEnum'] = {

    /**
     * value: "IN_PROGRESS"
     * @const
     */
    "IN_PROGRESS": "IN_PROGRESS",

    /**
     * value: "COMPLETED"
     * @const
     */
    "COMPLETED": "COMPLETED",

    /**
     * value: "NOT_STARTED"
     * @const
     */
    "NOT_STARTED": "NOT_STARTED"
};



export default DayInstance;

