/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FormBlueprint model module.
 * @module openapi/models/FormBlueprint
 * @version 1.0.0
 */
class FormBlueprint {
    /**
     * Constructs a new <code>FormBlueprint</code>.
     * @alias module:openapi/models/FormBlueprint
     * @param formBlueprintUuid {String} UUID for a Form Blueprint
     * @param title {String} 
     */
    constructor(formBlueprintUuid, title) { 
        
        FormBlueprint.initialize(this, formBlueprintUuid, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, formBlueprintUuid, title) { 
        obj['form_blueprint_uuid'] = formBlueprintUuid;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>FormBlueprint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:openapi/models/FormBlueprint} obj Optional instance to populate.
     * @return {module:openapi/models/FormBlueprint} The populated <code>FormBlueprint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FormBlueprint();

            if (data.hasOwnProperty('form_blueprint_uuid')) {
                obj['form_blueprint_uuid'] = ApiClient.convertToType(data['form_blueprint_uuid'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('callback_url')) {
                obj['callback_url'] = ApiClient.convertToType(data['callback_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FormBlueprint</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FormBlueprint</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FormBlueprint.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['form_blueprint_uuid'] && !(typeof data['form_blueprint_uuid'] === 'string' || data['form_blueprint_uuid'] instanceof String)) {
            throw new Error("Expected the field `form_blueprint_uuid` to be a primitive type in the JSON string but got " + data['form_blueprint_uuid']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['callback_url'] && !(typeof data['callback_url'] === 'string' || data['callback_url'] instanceof String)) {
            throw new Error("Expected the field `callback_url` to be a primitive type in the JSON string but got " + data['callback_url']);
        }

        return true;
    }


}

FormBlueprint.RequiredProperties = ["form_blueprint_uuid", "title"];

/**
 * UUID for a Form Blueprint
 * @member {String} form_blueprint_uuid
 */
FormBlueprint.prototype['form_blueprint_uuid'] = undefined;

/**
 * @member {String} title
 */
FormBlueprint.prototype['title'] = undefined;

/**
 * @member {String} description
 */
FormBlueprint.prototype['description'] = undefined;

/**
 * @member {String} callback_url
 */
FormBlueprint.prototype['callback_url'] = undefined;






export default FormBlueprint;

