/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProjectBlueprint from './ProjectBlueprint';
import ProjectInstance from './ProjectInstance';

/**
 * The ProjectDTO model module.
 * @module openapi/models/ProjectDTO
 * @version 1.0.0
 */
class ProjectDTO {
    /**
     * Constructs a new <code>ProjectDTO</code>.
     * @alias module:openapi/models/ProjectDTO
     * @param blueprint {module:openapi/models/ProjectBlueprint} 
     * @param instance {module:openapi/models/ProjectInstance} 
     */
    constructor(blueprint, instance) { 
        
        ProjectDTO.initialize(this, blueprint, instance);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, blueprint, instance) { 
        obj['blueprint'] = blueprint;
        obj['instance'] = instance;
    }

    /**
     * Constructs a <code>ProjectDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:openapi/models/ProjectDTO} obj Optional instance to populate.
     * @return {module:openapi/models/ProjectDTO} The populated <code>ProjectDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectDTO();

            if (data.hasOwnProperty('blueprint')) {
                obj['blueprint'] = ProjectBlueprint.constructFromObject(data['blueprint']);
            }
            if (data.hasOwnProperty('instance')) {
                obj['instance'] = ProjectInstance.constructFromObject(data['instance']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProjectDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProjectDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProjectDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `blueprint`
        if (data['blueprint']) { // data not null
          ProjectBlueprint.validateJSON(data['blueprint']);
        }
        // validate the optional field `instance`
        if (data['instance']) { // data not null
          ProjectInstance.validateJSON(data['instance']);
        }

        return true;
    }


}

ProjectDTO.RequiredProperties = ["blueprint", "instance"];

/**
 * @member {module:openapi/models/ProjectBlueprint} blueprint
 */
ProjectDTO.prototype['blueprint'] = undefined;

/**
 * @member {module:openapi/models/ProjectInstance} instance
 */
ProjectDTO.prototype['instance'] = undefined;






export default ProjectDTO;

