/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProjectDaysMapperId model module.
 * @module openapi/models/ProjectDaysMapperId
 * @version 1.0.0
 */
class ProjectDaysMapperId {
    /**
     * Constructs a new <code>ProjectDaysMapperId</code>.
     * Composite ID for ProjectDaysMapper
     * @alias module:openapi/models/ProjectDaysMapperId
     * @param projectBlueprintUuid {String} UUID for a Project Blueprint
     * @param dayBlueprintUuid {String} UUID for a Day Blueprint
     */
    constructor(projectBlueprintUuid, dayBlueprintUuid) { 
        
        ProjectDaysMapperId.initialize(this, projectBlueprintUuid, dayBlueprintUuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, projectBlueprintUuid, dayBlueprintUuid) { 
        obj['project_blueprint_uuid'] = projectBlueprintUuid;
        obj['day_blueprint_uuid'] = dayBlueprintUuid;
    }

    /**
     * Constructs a <code>ProjectDaysMapperId</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:openapi/models/ProjectDaysMapperId} obj Optional instance to populate.
     * @return {module:openapi/models/ProjectDaysMapperId} The populated <code>ProjectDaysMapperId</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectDaysMapperId();

            if (data.hasOwnProperty('project_blueprint_uuid')) {
                obj['project_blueprint_uuid'] = ApiClient.convertToType(data['project_blueprint_uuid'], 'String');
            }
            if (data.hasOwnProperty('day_blueprint_uuid')) {
                obj['day_blueprint_uuid'] = ApiClient.convertToType(data['day_blueprint_uuid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProjectDaysMapperId</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProjectDaysMapperId</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProjectDaysMapperId.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['project_blueprint_uuid'] && !(typeof data['project_blueprint_uuid'] === 'string' || data['project_blueprint_uuid'] instanceof String)) {
            throw new Error("Expected the field `project_blueprint_uuid` to be a primitive type in the JSON string but got " + data['project_blueprint_uuid']);
        }
        // ensure the json data is a string
        if (data['day_blueprint_uuid'] && !(typeof data['day_blueprint_uuid'] === 'string' || data['day_blueprint_uuid'] instanceof String)) {
            throw new Error("Expected the field `day_blueprint_uuid` to be a primitive type in the JSON string but got " + data['day_blueprint_uuid']);
        }

        return true;
    }


}

ProjectDaysMapperId.RequiredProperties = ["project_blueprint_uuid", "day_blueprint_uuid"];

/**
 * UUID for a Project Blueprint
 * @member {String} project_blueprint_uuid
 */
ProjectDaysMapperId.prototype['project_blueprint_uuid'] = undefined;

/**
 * UUID for a Day Blueprint
 * @member {String} day_blueprint_uuid
 */
ProjectDaysMapperId.prototype['day_blueprint_uuid'] = undefined;






export default ProjectDaysMapperId;

