/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProjectInstanceId from './ProjectInstanceId';

/**
 * The ProjectInstance model module.
 * @module openapi/models/ProjectInstance
 * @version 1.0.0
 */
class ProjectInstance {
    /**
     * Constructs a new <code>ProjectInstance</code>.
     * Entity for a user&#39;s specific project instance
     * @alias module:openapi/models/ProjectInstance
     * @param id {module:openapi/models/ProjectInstanceId} 
     * @param status {module:openapi/models/ProjectInstance.StatusEnum} 
     */
    constructor(id, status) { 
        
        ProjectInstance.initialize(this, id, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, status) { 
        obj['id'] = id;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>ProjectInstance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:openapi/models/ProjectInstance} obj Optional instance to populate.
     * @return {module:openapi/models/ProjectInstance} The populated <code>ProjectInstance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectInstance();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ProjectInstanceId.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Date');
            }
            if (data.hasOwnProperty('feedback')) {
                obj['feedback'] = ApiClient.convertToType(data['feedback'], 'String');
            }
            if (data.hasOwnProperty('what_went_well')) {
                obj['what_went_well'] = ApiClient.convertToType(data['what_went_well'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProjectInstance</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProjectInstance</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProjectInstance.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `id`
        if (data['id']) { // data not null
          ProjectInstanceId.validateJSON(data['id']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['feedback'] && !(typeof data['feedback'] === 'string' || data['feedback'] instanceof String)) {
            throw new Error("Expected the field `feedback` to be a primitive type in the JSON string but got " + data['feedback']);
        }
        // ensure the json data is a string
        if (data['what_went_well'] && !(typeof data['what_went_well'] === 'string' || data['what_went_well'] instanceof String)) {
            throw new Error("Expected the field `what_went_well` to be a primitive type in the JSON string but got " + data['what_went_well']);
        }

        return true;
    }


}

ProjectInstance.RequiredProperties = ["id", "status"];

/**
 * @member {module:openapi/models/ProjectInstanceId} id
 */
ProjectInstance.prototype['id'] = undefined;

/**
 * @member {module:openapi/models/ProjectInstance.StatusEnum} status
 */
ProjectInstance.prototype['status'] = undefined;

/**
 * @member {Date} start_date
 */
ProjectInstance.prototype['start_date'] = undefined;

/**
 * @member {Date} end_date
 */
ProjectInstance.prototype['end_date'] = undefined;

/**
 * @member {String} feedback
 */
ProjectInstance.prototype['feedback'] = undefined;

/**
 * @member {String} what_went_well
 */
ProjectInstance.prototype['what_went_well'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
ProjectInstance['StatusEnum'] = {

    /**
     * value: "IN_PROGRESS"
     * @const
     */
    "IN_PROGRESS": "IN_PROGRESS",

    /**
     * value: "COMPLETED"
     * @const
     */
    "COMPLETED": "COMPLETED"
};



export default ProjectInstance;

