/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TaskInstanceId from './TaskInstanceId';

/**
 * The TaskInstance model module.
 * @module openapi/models/TaskInstance
 * @version 1.0.0
 */
class TaskInstance {
    /**
     * Constructs a new <code>TaskInstance</code>.
     * User&#39;s progress for a specific task
     * @alias module:openapi/models/TaskInstance
     * @param id {module:openapi/models/TaskInstanceId} 
     * @param status {Boolean} True if completed, false otherwise
     */
    constructor(id, status) { 
        
        TaskInstance.initialize(this, id, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, status) { 
        obj['id'] = id;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>TaskInstance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:openapi/models/TaskInstance} obj Optional instance to populate.
     * @return {module:openapi/models/TaskInstance} The populated <code>TaskInstance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaskInstance();

            if (data.hasOwnProperty('id')) {
                obj['id'] = TaskInstanceId.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TaskInstance</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TaskInstance</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TaskInstance.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `id`
        if (data['id']) { // data not null
          TaskInstanceId.validateJSON(data['id']);
        }

        return true;
    }


}

TaskInstance.RequiredProperties = ["id", "status"];

/**
 * @member {module:openapi/models/TaskInstanceId} id
 */
TaskInstance.prototype['id'] = undefined;

/**
 * True if completed, false otherwise
 * @member {Boolean} status
 */
TaskInstance.prototype['status'] = undefined;






export default TaskInstance;

