/**
 * Project & Day API
 * An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DayBlueprint from './models/DayBlueprint';
import DayComponentsMapper from './models/DayComponentsMapper';
import DayComponentsMapperId from './models/DayComponentsMapperId';
import DayDTO from './models/DayDTO';
import DayInstance from './models/DayInstance';
import DayInstanceId from './models/DayInstanceId';
import Error from './models/Error';
import Field from './models/Field';
import Finances from './models/Finances';
import FinancesId from './models/FinancesId';
import FormBlueprint from './models/FormBlueprint';
import FormDTO from './models/FormDTO';
import FormFieldMapper from './models/FormFieldMapper';
import FormFieldMapperId from './models/FormFieldMapperId';
import FormInstance from './models/FormInstance';
import FormInstanceId from './models/FormInstanceId';
import Media from './models/Media';
import Members from './models/Members';
import MembersId from './models/MembersId';
import ProjectBlueprint from './models/ProjectBlueprint';
import ProjectDTO from './models/ProjectDTO';
import ProjectDaysMapper from './models/ProjectDaysMapper';
import ProjectDaysMapperId from './models/ProjectDaysMapperId';
import ProjectInstance from './models/ProjectInstance';
import ProjectInstanceId from './models/ProjectInstanceId';
import TaskBlueprint from './models/TaskBlueprint';
import TaskDTO from './models/TaskDTO';
import TaskInstance from './models/TaskInstance';
import TaskInstanceId from './models/TaskInstanceId';
import DefaultApi from './controllers/DefaultApi';


/**
* An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ProjectDayApi = require('openapi/index'); // See note below*.
* var xxxSvc = new ProjectDayApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ProjectDayApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['openapi/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ProjectDayApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ProjectDayApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module openapi/index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:openapi/ApiClient}
     */
    ApiClient,

    /**
     * The DayBlueprint model constructor.
     * @property {module:openapi/models/DayBlueprint}
     */
    DayBlueprint,

    /**
     * The DayComponentsMapper model constructor.
     * @property {module:openapi/models/DayComponentsMapper}
     */
    DayComponentsMapper,

    /**
     * The DayComponentsMapperId model constructor.
     * @property {module:openapi/models/DayComponentsMapperId}
     */
    DayComponentsMapperId,

    /**
     * The DayDTO model constructor.
     * @property {module:openapi/models/DayDTO}
     */
    DayDTO,

    /**
     * The DayInstance model constructor.
     * @property {module:openapi/models/DayInstance}
     */
    DayInstance,

    /**
     * The DayInstanceId model constructor.
     * @property {module:openapi/models/DayInstanceId}
     */
    DayInstanceId,

    /**
     * The Error model constructor.
     * @property {module:openapi/models/Error}
     */
    Error,

    /**
     * The Field model constructor.
     * @property {module:openapi/models/Field}
     */
    Field,

    /**
     * The Finances model constructor.
     * @property {module:openapi/models/Finances}
     */
    Finances,

    /**
     * The FinancesId model constructor.
     * @property {module:openapi/models/FinancesId}
     */
    FinancesId,

    /**
     * The FormBlueprint model constructor.
     * @property {module:openapi/models/FormBlueprint}
     */
    FormBlueprint,

    /**
     * The FormDTO model constructor.
     * @property {module:openapi/models/FormDTO}
     */
    FormDTO,

    /**
     * The FormFieldMapper model constructor.
     * @property {module:openapi/models/FormFieldMapper}
     */
    FormFieldMapper,

    /**
     * The FormFieldMapperId model constructor.
     * @property {module:openapi/models/FormFieldMapperId}
     */
    FormFieldMapperId,

    /**
     * The FormInstance model constructor.
     * @property {module:openapi/models/FormInstance}
     */
    FormInstance,

    /**
     * The FormInstanceId model constructor.
     * @property {module:openapi/models/FormInstanceId}
     */
    FormInstanceId,

    /**
     * The Media model constructor.
     * @property {module:openapi/models/Media}
     */
    Media,

    /**
     * The Members model constructor.
     * @property {module:openapi/models/Members}
     */
    Members,

    /**
     * The MembersId model constructor.
     * @property {module:openapi/models/MembersId}
     */
    MembersId,

    /**
     * The ProjectBlueprint model constructor.
     * @property {module:openapi/models/ProjectBlueprint}
     */
    ProjectBlueprint,

    /**
     * The ProjectDTO model constructor.
     * @property {module:openapi/models/ProjectDTO}
     */
    ProjectDTO,

    /**
     * The ProjectDaysMapper model constructor.
     * @property {module:openapi/models/ProjectDaysMapper}
     */
    ProjectDaysMapper,

    /**
     * The ProjectDaysMapperId model constructor.
     * @property {module:openapi/models/ProjectDaysMapperId}
     */
    ProjectDaysMapperId,

    /**
     * The ProjectInstance model constructor.
     * @property {module:openapi/models/ProjectInstance}
     */
    ProjectInstance,

    /**
     * The ProjectInstanceId model constructor.
     * @property {module:openapi/models/ProjectInstanceId}
     */
    ProjectInstanceId,

    /**
     * The TaskBlueprint model constructor.
     * @property {module:openapi/models/TaskBlueprint}
     */
    TaskBlueprint,

    /**
     * The TaskDTO model constructor.
     * @property {module:openapi/models/TaskDTO}
     */
    TaskDTO,

    /**
     * The TaskInstance model constructor.
     * @property {module:openapi/models/TaskInstance}
     */
    TaskInstance,

    /**
     * The TaskInstanceId model constructor.
     * @property {module:openapi/models/TaskInstanceId}
     */
    TaskInstanceId,

    /**
    * The DefaultApi service constructor.
    * @property {module:openapi/controllers/DefaultApi}
    */
    DefaultApi
};
